### ISSUE TITLE
Help to use

### ISSUE THREAD

**Issue by Alessio-R** [Fanaen/Hunspell2WordList#1]
Hi, this isn't an issue but a request to help.
Sorry for that, but I'm not an expert and, since I think that your application could help me a lot, I need to use it but I don't know how to do. I have both the .dic and .aff from the dictionary that I need to obtain.

**Comment by Fanaen** [comment]
No need for apologies. The instructions are rather succinct.

First, you'll need a Java runtime on your computer. Depending on your platform, you can get it [here](http://www.java.com/en/download/manual.jsp) or install it with your package manager (on GNU/Linux for example).

Then, [download the latest version](http://storage.fanaen.fr/Projects/2015.Hunspell2WordList/) and extract it the folder of your choice. Put the _.dic/.aff_ files in a subfolder named **data**.

Then, open a terminal/shell/command-line (`cmd.exe` on Windows, reach it via research on start menu) and go to this folder with the command `cd`. Now you can write the command as described in [the project readme](https://github.com/Fanaen/Hunspell2WordList), where dictionaryName is the name of your files.

Is that better ?

**Comment by Alessio-R** [comment]
Thank you, I did all that you said but it returns me this error: "unable to access jarfile hunspell2wordlist"

**Comment by Fanaen** [comment]
On which platform do you work (Windows/Linux/Mac OSX/etc.) ? 

Two possibilities. Either the terminal isn't in the folder of the _.jar_ file or it doesn't recognise it.
Try with the exact case instead.

``` shell
java -jar Hunspell2WordList.jar data/dictionaryName outputFile.txt
```

**Comment by Alessio-R** [comment]
I'm on windows. The terminal is on the main folder (which I called "Hunspell2" and contains Hunspell2WordList.jar, license, readme.md and the data folder). It doesn't work neither with the exact case.

**Comment by Fanaen** [comment]
Weird. I have to admit I'm a bit lost.
Maybe you can try with the absolute path like this, but this isn't supposed to change anything:

``` shell
java -jar "C:\path\to\folder\Hunspell2WordList.jar" data/dictionaryName outputFile.txt
```

Another possibility is to try with the other version (v0.1.0).

**Comment by Alessio-R** [comment]
Nothing, it gives me the same error, even with the older version. For now I would like to thank you for your help: I hope to resolve this problem, because your application could be very useful for me.

**Comment by Alessio-R** [comment]
I finally resolved the problem by reinstalling the java environment: it seems to work correctly with an italian dictionary (https://github.com/elastic/hunspell/tree/master/dicts/it_IT-moz), although I can't find the output, even expressing the complete path of the desidered file (c:...). However it seems to have problems with this ancient greek dictionary: http://extensions.openoffice.org/en/project/ancient-greek-spell-checker. For me is very important to have a complete output of that dictionary. Again, thank you for your help.

**Comment by Fanaen** [comment]
You're welcome.
The program was not designed to work with absolute paths, so you should avoid this if possible. The output is either the console or the named file.

Can you send the errors, please ?

**Comment by Alessio-R** [comment]
Yes, but it didn't create the named file! Here is a pic of the result: http://imgur.com/vtzKWc9

**Comment by Fanaen** [comment]
It seams that the it_IT files uses _ISO8859-15_ encoding and H2WL can't handle it.
However, it is possible to convert these files to _UTF-8_ to fix this issue. The simplest way to do that is to install [Notepad++](https://notepad-plus-plus.org/), open each file and click on `Encoding > Convert to UTF-8`.

Where are the _.dic/.aff_ files for the ancient greek dictionary?

**Comment by Alessio-R** [comment]
I converted in UTF-8 and it worked for the it_IT (I had to write data/ita.txt in the shell to obtain the txt file). The ancient greek package is here: http://members.hellug.gr/sng/ancientgreekoxt/download.html, you must open with zip and extract the .dic and .aff

**Comment by Fanaen** [comment]
Thanks. The [new version (v0.1.2)](http://storage.fanaen.fr/Projects/2015.Hunspell2WordList/) should solve the issue.

Note that you can also use the command without any argument, like this:

``` shell
$ java -jar Hunspell2WordList.jar
Command help: hunspell2wordlist [InputFilePath] [OutputFilePath]
Enter the input file's path: data/grc_GR
Enter the output file's path: grc.txt
References stats:
 * 0 AM references
 * 0 AF references
 * 5000 affixes
 * 5000 affix options
DicParser stats:
 * 760186 lines
WordListGenerator stats:
 * 1784034 words
```

**Comment by Alessio-R** [comment]
Thank you very much, it has worked perfectly. This application resolved a big problem for me: obtain a multilingual spell checker to use with TeXStudio (a LaTeX editor). In fact, while all other dictionaries were merged correctly with hunspell-merge (https://github.com/arty-name/hunspell-merge), the ancient greek suffered a problem with the affixes. Now I put all the greek words in the .dic file of the merged dictionaries, without affixes, and it works perfectly in combination with the other languages. Your help is very appreciated, I hope that your application will obtain the appreciation that deserves.

**Comment by Fanaen** [comment]
This merge problem is probably the same than for H2WL. The greek dictionary uses numeric references for affix which is usually used for something else. 

Just keep in mind that the result of H2WL is far from perfect. However, I am glad that my little side-project helped.
Thank you for your kind words.
